# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('link', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
