# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={},
        ),
        migrations.RemoveField(
            model_name='feed',
            name='pub_date',
        ),
    ]
